version: '3.8'

services:
  maven:
    build: maven/
    volumes:
      - tomcat_webapps:/shared_folder:rw

  tomcat:
    image: tomcat:10.1-jre11-openjdk-slim
    volumes:
      - tomcat_webapps:/usr/local/tomcat/webapps:rw
    ports: 
      - "8080:8080"

volumes:
  tomcat_webapps:
